export { RealFFT } from './fft';
export { detectOnsets } from './OnsetDetector';
export type { Onset, OnsetOptions, OnsetResult } from './OnsetDetector';
export { estimateBpm } from './BpmEstimator';
export type { BpmEstimate } from './BpmEstimator';
export { trackBeats, estimateDownbeatPhase } from './BeatTracker';
export { analyzeSong, STEPS_PER_BAR, STEPS_PER_BEAT, BEATS_PER_BAR } from './SongAnalyzer';
export type { Slot, SongAnalysis, AnalysisStage } from './SongAnalyzer';
export { composeChart, rateStars, scoreTemplate, salience, chartFeatures, TEMPLATES } from './ChartGenerator';
export type { ComposeOptions, Template, Category } from './ChartGenerator';
