export { RealFFT } from './fft';
export { detectOnsets } from './OnsetDetector';
export type { Onset, OnsetOptions, OnsetResult } from './OnsetDetector';
export { estimateBpm } from './BpmEstimator';
export type { BpmEstimate } from './BpmEstimator';
export { trackBeats, estimateDownbeatPhase } from './BeatTracker';
export { analyzeSong, STEPS_PER_BAR, STEPS_PER_BEAT, BEATS_PER_BAR } from './SongAnalyzer';
export type { Slot, SongAnalysis, AnalysisStage } from './SongAnalyzer';
export { composeChart, chartBarTimes } from './ChartGenerator';
export type { ComposeOptions, ComposeTrace, RollPolicy } from './ChartGenerator';
export { salience, PHRASE_BARS } from './bars';
export { figureOf } from './figure';
export type { Figure } from './figure';
export { circleSpread, handOf } from './laneAssign';
export { rateStars, chartFeatures } from './stars';
export { BUDGETS, MAX_STARS, FAST_RATE, CHAPTER_RANGE, gapSlots, foldBpm, songEnergy, targetStars, budgetFeatures, failsAt, rateStarsBudget } from './budget';
export type { Budget, BudgetFeatures, Chapter, SongEnergy } from './budget';
export { assertPlayable, worstWindowStars } from './playability';
export { layerEnergy, layerStrengths, presentLayers, ringAt, LAYERS } from './layers';
export type { Layer, LayerStrengths, StemLayers } from './layers';
