/** Catalog entry — generated by `scripts/generate-charts.ts` into `catalog.json`, sorted by stars. */
export interface TrackMeta {
  id: string;
  title: string;
  artist: string;
  license: string;
  sourceUrl: string;
  bpm: number;
  duration: number;
  /** Difficulty of the song's chart, 1–10. */
  stars: number;
  notes: number;
  /** Quick mechanic summary shown on the card. */
  features: { circles: number; rolls: number; slides: number; holds: number; laneChanges: number };
}
