import type { Difficulty } from '@/shared/config/constants';
import type { WorldId } from '@/shared/types/world';

/** Catalog entry — generated by `scripts/generate-charts.ts` into `catalog.json`. */
export interface TrackMeta {
  id: string;
  title: string;
  artist: string;
  license: string;
  sourceUrl: string;
  world: WorldId;
  bpm: number;
  duration: number;
  stars: Record<Difficulty, number>;
  notes: Record<Difficulty, number>;
}
