import type { Genre } from '@/shared/types/chart';

/** Catalog entry — generated by `scripts/generate-charts.ts` into `catalog.json`, sorted by stars. */
export interface TrackMeta {
  id: string;
  title: string;
  artist: string;
  license: string;
  sourceUrl: string;
  genre: Genre;
  /** Premium track — sold in the shop for crystals; absent for the free catalog. */
  premium?: boolean;
  /** Named pack (`rock`) — a chapter of its own after the numbered ones; absent for the main catalog. */
  pack?: string;
  bpm: number;
  duration: number;
  /** Difficulty of the song's chart, 1–10. */
  stars: number;
  notes: number;
  /** Quick mechanic summary shown on the card. */
  features: { circles: number; rolls: number; slides: number; holds: number; laneChanges: number };
}
